name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    name: windows-latest / ${{ matrix.build_type }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg .\vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure CMake
        shell: pwsh
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure