name: Build

on:
  push:
    branches: [main, dev]
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup SDL
        id: sdl
        uses: libsdl-org/setup-sdl@main
        with:
          version: 2-latest
          install-linux-dependencies: true

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure